### PR TITLE
add xScale / yScale prop support

### PR DESCRIPTION
**Pull request by devholic**
Hi, I think custom xScale and yScale support can be helpful to set min / max value for x,y.
So, I added xScale / yScale support to 
- AreaChart
- BarChart
- CandlestickChart
- LineChart
- ScatterChart

### CODE REVIEW

**Comment by yang-wei** [comment]
You are right but the more correct way to do this will be creating another layer of abstraction for xScale and yScale (maybe in the cartesian prop mixin ?)

**Comment by devholic** [comment]
@yang-wei I checked charts using xScale / yScale,
- AreaChart
- BarChart
- CandlestickChart
- LineChart
- ScatterChart

I found that these chart using CartesianChartPropsMixin, which is mentioned in your comment.
So I added xScale / yScale property to CartesianChartPropsMixin. 😄

**Comment by yang-wei** [comment]
lgtm =)

**Comment by devholic** [comment]
Thanks :D

**Pull request merged**
