### PR TITLE
Build & React updates

### PR DESCRIPTION
**Pull request by drtz**
- Updated to React 15 (removing calls to the deprecated `getDOMNode()`)
- Use gulp-babel instead of the deprecated gulp-react
- Updated browserify and babelify to their latest releases

### CODE REVIEW

**Comment by yang-wei** [comment]
I was actually doing the same thing on dev branch but since you updated to babel 6 and removing the `getDOMNode()` I will merge yours first.

**Comment by yang-wei** [comment]
running `npm run release` gives me:

```
Loading plugins: 832.952ms
[16:22:15] Using gulpfile ~/code/rd3/gulpfile.js
[16:22:15] Starting 'copymisc'...
[16:22:15] Starting 'clean:build'...
[16:22:15] Finished 'clean:build' after 32 ms
[16:22:15] Starting 'minified'...

SyntaxError: /Users/l-wei/code/rd3/src/piechart/PieChart.jsx: Unexpected token (52:6) while parsing file: /Users/l-wei/code/rd3/src/piechart/PieChart.jsx
[16:22:16] Finished 'minified' after 1.02 s
SyntaxError: /Users/l-wei/code/rd3/src/linechart/LineChart.jsx: Unexpected token (60:6) while parsing file: /Users/l-wei/code/rd3/src/linechart/LineChart.jsx
SyntaxError: /Users/l-wei/code/rd3/src/barchart/BarChart.jsx: Unexpected token (107:6) while parsing file: /Users/l-wei/code/rd3/src/barchart/BarChart.jsx
SyntaxError: /Users/l-wei/code/rd3/src/areachart/AreaChart.jsx: Unexpected token (98:10) while parsing file: /Users/l-wei/code/rd3/src/areachart/AreaChart.jsx
SyntaxError: /Users/l-wei/code/rd3/src/candlestick/CandlestickChart.jsx: Unexpected token (71:10) while parsing file: /Users/l-wei/code/rd3/src/candlestick/CandlestickChart.jsx
SyntaxError: /Users/l-wei/code/rd3/src/scatterchart/ScatterChart.jsx: Unexpected token (67:6) while parsing file: /Users/l-wei/code/rd3/src/scatterchart/ScatterChart.jsx
SyntaxError: /Users/l-wei/code/rd3/src/treemap/Treemap.jsx: Unexpected token (47:6) while parsing file: /Users/l-wei/code/rd3/src/treemap/Treemap.jsx
```

```
➜  rd3 git:(master) node -v
v5.10.1
➜  rd3 git:(master) npm -v
3.8.3
```

**Comment by drtz** [comment]
Sorry that's my fault! 6e2bfec should take care of it

**Comment by yang-wei** [comment]
@drtz Build is fine now but running `npm test` will fail. Do you want to fix this or I can continue your work.

**Comment by yang-wei** [comment]
moved to  #15

**Pull request closed without merging**
