### PR TITLE
Adding common components to package exports

### PR DESCRIPTION
**Pull request by solomon-gumball**
So this is a very manual way of exporting these common components.

Alternatively we could export these under a namespace that's separate from the charts (though I'm not a huge fan of this):

``` js
module.exports.common = require('./common');
```

What I think is the best option though is to include the source files in the npm package so they can be imported individually like in React Toolbox:

``` js
var XAxis = require('rd3/common/XAxis');
```

Let me know what you think.

### CODE REVIEW

**Comment by yang-wei** [comment]
I am good with this option. 

> var XAxis = require('rd3/common/XAxis');

I think you can do something like this now to get the same thing:

``` js
var XAxis = require('rd3/src/common/XAxis');
```

**Comment by solomon-gumball** [comment]
The npm module only includes the 'build' directory, so you couldn't do that when installing via npm.  

What do you think about adding 'src' here too to address that?

https://github.com/yang-wei/rd3/blob/master/package.json#L99

**Comment by yang-wei** [comment]
> What do you think about adding 'src' here too to address that?

Adding src to package.json files field will be a better option for me.
Indeed we can stop exporting all modules in [rds/index.js](https://github.com/redwoodfavorite/rd3/blob/363ac4e917d2a58c2d3f2036be6118bec191a669/src/index.js)

**Comment by solomon-gumball** [comment]
@yang-wei I removed the extra exports from `index.js` and just added the 'src' directory to the files field in package.json.  So if people want to use the common components they can just import them directly.

I do think it's nice to keep exporting the standard modules from `index.js` because it allows you to publish the minified build.

**Comment by yang-wei** [comment]
LGTM ! Will publish a new release soon

**Pull request merged**
