### PR TITLE
Tick stroke and tick text stroke properties in charts

### PR DESCRIPTION
**Pull request by arisgk**
I could not change the tick stroke and tick text stroke using properties. Adding them as props in chart components did the trick. I added tickTextStroke into axis components propTypes too. It is my very first open source contribution so tell me if I did anything wrong in the process.

### CODE REVIEW

**Comment by yang-wei** [comment]
oh @arisgk thanks for this but instead of adding each propTypes to each chart, I prefer you to add them to [CartesianChartPropsMixin.js](https://github.com/yang-wei/rd3/blob/master/src/mixins/CartesianChartPropsMixin.js)

You can take a look how this is done in another pr - https://github.com/yang-wei/rd3/pull/27

And also welcome to OSS

**Comment by arisgk** [comment]
Okay, @yang-wei do you think it is better to go for separate `xAxisTickStroke` and `yAxisTickStroke` or a common `tickStroke` prop for both axes?

**Comment by yang-wei** [comment]
separate will be fine since this is how our API looks like

**Comment by arisgk** [comment]
@yang-wei I added `xAxisTickStroke`, `xAxisTickTextStroke`, `yAxisTickStroke`, `yAxisTickTextStroke` to [CartesianChartPropsMixin.js](https://github.com/yang-wei/rd3/blob/master/src/mixins/CartesianChartPropsMixin.js).

**Comment by yang-wei** [comment]
will merge in #70

**Pull request closed without merging**
