### PR TITLE
Add eslint airbnb config

### PR DESCRIPTION
**Pull request by jonase**
- 'npm run lint' to run the linter
- 'npm run lint:fix' to run the linter and fix errors & warnings that can be automatically fixable
- Resolve automatically fixable lint errors & warnings

### CODE REVIEW

**Comment by jonase** [comment]
@yang-wei This PR does not resolve all errors/warnings. Do you want these resolved in this initial PR as well?

**Comment by yang-wei** [comment]
Everything looks good to me.

>  Do you want these resolved in this initial PR as well?

This will be cool and I will merge this once its done.

I will be offline for 3 days from tomorrow but I will merge it asap once it's done =)

**Comment by yang-wei** [comment]
@jonase Hey thanks for it. I tried it on local and realise we need to resolve a lot of lint error manually. Do you plan to solve it or I can take care of them?

**Comment by jonase** [comment]
@yang-wei I've been planning to resolve the last of them. Hopefully I don't break anything and the tests still pass. I would also need to test at least the examples before we merge.

**Comment by jonase** [comment]
@yang-wei 
I disabled the rules 
- react/prefer-es6-class
- react/prefer-stateless-function 
- strict 
  rules as I didn't know if you prefer these or not. We can enable then later. 

Could you take a look at the last remaining eslint errors? I didn't want to refactor code with a high risk of breaking something. Note that some of the obvious fixes (for example `!=` to `!==`) will break the tests

**Comment by yang-wei** [comment]
Thanks for you efforts. Everything is ok but since you include `react-addons-test-utils` package so `react ^0.15.1` is needed. And from there on test broke but I am fixing it over [here](https://github.com/yang-wei/rd3/pull/15). 

For the last part of errors I will fix them quickly =)

When #15 is done, I will resolve the conflicts and merge them manually.

**Comment by yang-wei** [comment]
> strict rules as I didn't know if you prefer these or not. We can enable then later.

It's fine for now =)

**Comment by yang-wei** [comment]
resolved in #16

**Pull request closed without merging**
