### PR TITLE
changes to elimate deprication warnings from react. Introduces two ne…

### PR DESCRIPTION
**Pull request by brantphoto**
for yang-wei/rd3/issues/106

@yang-wei This pull request replaces React.PropTypes and React.createClass(). Note that that means that there are now two more dependencies, 'create-react-class' and 'prop-types', so I would consider that when figuring out the version number.

### CODE REVIEW

**Comment by brantphoto** [comment]
Well, the CI build failed due to the linting... I see two possibilities for fixing the linting. Change eslint rules or potentially make the proptypes required. Any suggestions?

**Comment by brantphoto** [comment]
@yang-wei does this look ok? Are you still taking pull requests or is there another maintainer? Thanks in advance.

**Comment by brantphoto** [comment]
Hi @yang-wei, just wanted to check in to see if this PR is acceptable. If you aren't maintaining the repo can you reply so I'll know to fork? Thanks!

**Comment by yang-wei** [comment]
@brantphoto Wow thanks for this pull request. I will definitely accept this and really apologize for the late response. Just want to check if any files is missing and will definitely give this a go

**Comment by yang-wei** [comment]
will make this into 0.8.0 version =)

**Pull request merged**
